/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface KontorEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "arbitrators"
      | "createTrade"
      | "feeBasisPoints"
      | "feeTreasury"
      | "fundTrade"
      | "hasVoted"
      | "nextTradeId"
      | "owner"
      | "raiseDispute"
      | "releaseFunds"
      | "renounceOwnership"
      | "setArbitrators"
      | "trades"
      | "transferOwnership"
      | "voteDispute"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ArbitratorVoted"
      | "DisputeRaised"
      | "DisputeResolved"
      | "OwnershipTransferred"
      | "TradeCompleted"
      | "TradeCreated"
      | "TradeFunded"
      | "TradePartialReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "arbitrators",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTrade",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feeBasisPoints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundTrade",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTradeId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFunds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setArbitrators",
    values: [[AddressLike, AddressLike, AddressLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "trades",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteDispute",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "arbitrators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeBasisPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundTrade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextTradeId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setArbitrators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trades", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteDispute",
    data: BytesLike
  ): Result;
}

export namespace ArbitratorVotedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    arbitrator: AddressLike,
    refundBuyer: boolean
  ];
  export type OutputTuple = [
    tradeId: bigint,
    arbitrator: string,
    refundBuyer: boolean
  ];
  export interface OutputObject {
    tradeId: bigint;
    arbitrator: string;
    refundBuyer: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [tradeId: BigNumberish, raisedBy: AddressLike];
  export type OutputTuple = [tradeId: bigint, raisedBy: string];
  export interface OutputObject {
    tradeId: bigint;
    raisedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [tradeId: BigNumberish, refundBuyer: boolean];
  export type OutputTuple = [tradeId: bigint, refundBuyer: boolean];
  export interface OutputObject {
    tradeId: bigint;
    refundBuyer: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeCompletedEvent {
  export type InputTuple = [tradeId: BigNumberish];
  export type OutputTuple = [tradeId: bigint];
  export interface OutputObject {
    tradeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeCreatedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    tradeId: bigint,
    buyer: string,
    seller: string,
    amount: bigint
  ];
  export interface OutputObject {
    tradeId: bigint;
    buyer: string;
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeFundedEvent {
  export type InputTuple = [tradeId: BigNumberish];
  export type OutputTuple = [tradeId: bigint];
  export interface OutputObject {
    tradeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradePartialReleasedEvent {
  export type InputTuple = [tradeId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [tradeId: bigint, amount: bigint];
  export interface OutputObject {
    tradeId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KontorEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): KontorEscrow;
  waitForDeployment(): Promise<this>;

  interface: KontorEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  arbitrators: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createTrade: TypedContractMethod<
    [
      _buyer: AddressLike,
      _oracle: AddressLike,
      _amount: BigNumberish,
      _tokenAddress: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  feeBasisPoints: TypedContractMethod<[], [bigint], "view">;

  feeTreasury: TypedContractMethod<[], [string], "view">;

  fundTrade: TypedContractMethod<
    [_tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  nextTradeId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  raiseDispute: TypedContractMethod<
    [_tradeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseFunds: TypedContractMethod<
    [_tradeId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setArbitrators: TypedContractMethod<
    [_newArbitrators: [AddressLike, AddressLike, AddressLike]],
    [void],
    "nonpayable"
  >;

  trades: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        buyer: string;
        seller: string;
        oracle: string;
        totalAmount: bigint;
        releasedAmount: bigint;
        token: string;
        status: bigint;
        votesForBuyer: bigint;
        votesForSeller: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  voteDispute: TypedContractMethod<
    [_tradeId: BigNumberish, refundBuyer: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "arbitrators"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createTrade"
  ): TypedContractMethod<
    [
      _buyer: AddressLike,
      _oracle: AddressLike,
      _amount: BigNumberish,
      _tokenAddress: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeBasisPoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundTrade"
  ): TypedContractMethod<[_tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextTradeId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[_tradeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseFunds"
  ): TypedContractMethod<
    [_tradeId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setArbitrators"
  ): TypedContractMethod<
    [_newArbitrators: [AddressLike, AddressLike, AddressLike]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trades"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        buyer: string;
        seller: string;
        oracle: string;
        totalAmount: bigint;
        releasedAmount: bigint;
        token: string;
        status: bigint;
        votesForBuyer: bigint;
        votesForSeller: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voteDispute"
  ): TypedContractMethod<
    [_tradeId: BigNumberish, refundBuyer: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ArbitratorVoted"
  ): TypedContractEvent<
    ArbitratorVotedEvent.InputTuple,
    ArbitratorVotedEvent.OutputTuple,
    ArbitratorVotedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TradeCompleted"
  ): TypedContractEvent<
    TradeCompletedEvent.InputTuple,
    TradeCompletedEvent.OutputTuple,
    TradeCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TradeCreated"
  ): TypedContractEvent<
    TradeCreatedEvent.InputTuple,
    TradeCreatedEvent.OutputTuple,
    TradeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TradeFunded"
  ): TypedContractEvent<
    TradeFundedEvent.InputTuple,
    TradeFundedEvent.OutputTuple,
    TradeFundedEvent.OutputObject
  >;
  getEvent(
    key: "TradePartialReleased"
  ): TypedContractEvent<
    TradePartialReleasedEvent.InputTuple,
    TradePartialReleasedEvent.OutputTuple,
    TradePartialReleasedEvent.OutputObject
  >;

  filters: {
    "ArbitratorVoted(uint256,address,bool)": TypedContractEvent<
      ArbitratorVotedEvent.InputTuple,
      ArbitratorVotedEvent.OutputTuple,
      ArbitratorVotedEvent.OutputObject
    >;
    ArbitratorVoted: TypedContractEvent<
      ArbitratorVotedEvent.InputTuple,
      ArbitratorVotedEvent.OutputTuple,
      ArbitratorVotedEvent.OutputObject
    >;

    "DisputeRaised(uint256,address)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(uint256,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TradeCompleted(uint256)": TypedContractEvent<
      TradeCompletedEvent.InputTuple,
      TradeCompletedEvent.OutputTuple,
      TradeCompletedEvent.OutputObject
    >;
    TradeCompleted: TypedContractEvent<
      TradeCompletedEvent.InputTuple,
      TradeCompletedEvent.OutputTuple,
      TradeCompletedEvent.OutputObject
    >;

    "TradeCreated(uint256,address,address,uint256)": TypedContractEvent<
      TradeCreatedEvent.InputTuple,
      TradeCreatedEvent.OutputTuple,
      TradeCreatedEvent.OutputObject
    >;
    TradeCreated: TypedContractEvent<
      TradeCreatedEvent.InputTuple,
      TradeCreatedEvent.OutputTuple,
      TradeCreatedEvent.OutputObject
    >;

    "TradeFunded(uint256)": TypedContractEvent<
      TradeFundedEvent.InputTuple,
      TradeFundedEvent.OutputTuple,
      TradeFundedEvent.OutputObject
    >;
    TradeFunded: TypedContractEvent<
      TradeFundedEvent.InputTuple,
      TradeFundedEvent.OutputTuple,
      TradeFundedEvent.OutputObject
    >;

    "TradePartialReleased(uint256,uint256)": TypedContractEvent<
      TradePartialReleasedEvent.InputTuple,
      TradePartialReleasedEvent.OutputTuple,
      TradePartialReleasedEvent.OutputObject
    >;
    TradePartialReleased: TypedContractEvent<
      TradePartialReleasedEvent.InputTuple,
      TradePartialReleasedEvent.OutputTuple,
      TradePartialReleasedEvent.OutputObject
    >;
  };
}
