/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { KontorEscrow__factory } from "./KontorEscrow__factory";
export { TestUSDC__factory } from "./TestUSDC__factory";
